[package]
name = "graphics-3d"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
glam = { version = "0.29.2", features = ["rand"] }
rand = "0.9"
rayon = "1.10.0"
softbuffer = "0.4.5"
winit = "0.30.5"
